openapi: 3.0.0
info:
  title: Transactions Service
  version: 1.0.0
  description: Add credit/debit transactions

paths:
  /transactions:
    post:
      summary: Add transaction
      description: Add transaction
      requestBody:
        $ref: "#/components/requestBodies/addTransaction"
      responses:
        "200":
          description: OK
components:
  schemas:
    addTransaction:
      description: A JSON request body containing the information needed to add a transaction
      type: object
      properties:
        amount:
          type: number
        account_id:
          type: number
        category:
          type: string
  requestBodies:
    addTransaction:
      description: A JSON request body containing information needed to add a transaction
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/addTransaction"